name: Simons
favicon: null
layout_spectrum: 0.99483
typography_spectrum: 0.4154841108247638
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.9183501007501036
  saturation: 0.07198944897390902
  rhythmicContrast: 0.7014013153966516
purpose: []
